# Generated by Django 4.0.3 on 2022-04-10 18:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='Dni')),
                ('fecha_nac', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha De Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Venta')),
                ('subTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, max_length=12, verbose_name='Sub Total')),
                ('iva', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Iva')),
                ('total', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Total')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Cantidad')),
                ('precio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Precio')),
                ('subTotal', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Sub Total')),
                ('id_produc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.venta')),
            ],
            options={
                'verbose_name': 'Det Venta',
                'verbose_name_plural': 'Det Ventas',
                'ordering': ['id'],
            },
        ),
    ]
