# Generated by Django 4.0.3 on 2022-04-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detventa',
            name='id_produc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.producto'),
        ),
        migrations.AlterField(
            model_name='detventa',
            name='id_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.categoria'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.cliente'),
        ),
    ]
