# Generated by Django 4.0.3 on 2022-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_detventa_id_produc_alter_detventa_id_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
