# Generated by Django 4.0.3 on 2022-04-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_producto_desc_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='desc',
        ),
    ]
