# Generated by Django 4.0.3 on 2022-04-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_producto_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(null=True, upload_to='img/product/', verbose_name='Image'),
        ),
    ]
